version : '3.3'

services :
  graph-visualisation : 
    image : graph_vis
    build :
      context : .
      dockerfile : ./Dockerfile.yml
    environment : 
      NODE_ENV : dev
    ports :
      - 3000:3000